swagger: '2.0'
info:
  description: REST API for Mytheresa Product Search
  version: 1.0.0-alpha
  title: Mytheresa product search
host: virtserver.swaggerhub.com
schemes:
  - https
definitions:
  Price:
    type: object
    properties:
      original:
        type: integer
      currency:
        type: string
      final:
        type: integer
      discount_percentage:
        type: string
        
  Product:
    properties:
      id:
        type: integer
      sku:
        type: string
      name:
        type: string
      category:
        type: string
      price:
        type: object
        $ref: '#/definitions/Price'
  Error:
    type: object
    properties:
      name:
        type: string
      message:
        type: string
      code:
        type: integer
        format: int32
      status:
        type: integer
        format: int32
responses:
  NotFound:
    description: Product not found
    schema:
      $ref: '#/definitions/Error'
  NotAcceptable:
    description: Category filter is missing in search
    schema:
      $ref: '#/definitions/Error'

paths:
  /products:
    get:
      tags:
        - Product
      summary: 'Get list of products'
      description: 'Return list of product.'
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters: 
        - in: query
          name: category
          type: string
          required: true
          description: Search by category
        - in: query
          name: price
          type: integer
          description: Search by price
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Product'
        404:
          $ref: '#/responses/NotFound'
        406:
          $ref: '#/responses/NotAcceptable'
  